version: "3.9"

services:
  postgres:
    image: postgres:15.4
    container_name: "toya-postgres"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: "toya-minio"
    volumes:
      - ./minio:/data
    ports:
      - "${MINIO_ADMIN_PORT}:${MINIO_ADMIN_PORT}"
      - "3003:9000"
    networks:
      - app_network
    environment:
      - MINIO_ROOT_USER=${ADMIN_USER}
      - MINIO_ROOT_PASSWORD=${ADMIN_PASSWORD}
    command: server /data --console-address ":${MINIO_ADMIN_PORT}"
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    links:
      - minio
      - postgres
    networks:
      - app_network
    env_file:
      - .env.docker
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    links:
      - api
    networks:
      - app_network
    env_file:
      - .env.docker

networks:
  app_network:
