services:
  postgres:
    image: postgres:15.4
    container_name: "toya-postgres"
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: "toya-minio"
    volumes:
      - ./minio:/data
    ports:
      - "3002:9090"
      - "3003:9000"
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER="${ADMIN_USER}"
      - MINIO_ROOT_PASSWORD="${ADMIN_PASSWORD}"
    networks:
      - app_network
    command: server /data --console-address ":9090"
    profiles:
      - minio


networks:
  app_network: