export * from "@prisma/client"
export enum ERRORS {
  PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
  UNKNOWN_ERROR="UNKNOWN_ERROR",
  NOT_FOUND="NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  PHONE_CONFIRM_ALREADY_CREATED = "PHONE_CONFIRM_ALREADY_CREATED",
  PHONE_CONFIRM_NOT_EXIST = "PHONE_CONFIRM_NOT_EXIST",
  PHONE_CONFIRM_NOT_UNCONFIRMED = "PHONE_CONFIRM_NOT_UNCONFIRMED",
  MAIL_CONFIRM_NOT_EXIST = "MAIL_CONFIRM_NOT_EXIST",
  MAIL_CONFIRM_BAD_CODE = "MAIL_CONFIRM_BAD_CODE",
  PHONE_UNCONFIRMED = "PHONE_UNCONFIRMED",
  ONLY_PNG_ALLOWED = "ONLY_PNG_ALLOWED",
  TEMPLATE_NOT_FOUND = "TEMPLATE_NOT_FOUND",
  TIME_IS_UP = "TIME_IS_UP",
  HASH_MISMATCH = "HASH_MISMATCH",
}