-- CreateEnum
CREATE TYPE "PROJECT_ROLES" AS ENUM ('OWNER', 'DEVELOPER', 'QUALITY_ASSURANCE', 'PROJECT_MANAGER', 'GUEST');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "avatarUrl" TEXT;

-- AlterTable
ALTER TABLE "ProjectMember" ADD COLUMN     "role" "PROJECT_ROLES" NOT NULL DEFAULT 'GUEST';
